# **Numpy**

In [1]:
import numpy as np

## **Phase 1: Creating Arrays**

1.1 Create a 1D Array

In [2]:
# Create a 1D array
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


1.2 Create a 2D Array

In [3]:
# Create a 2D array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


1.3 Create a 3D Array

In [4]:
# Create a 3D array
arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


1.4 Check Array Type

In [5]:
# Check array type
arr=np.array([10,20,30])
print(type(arr))

<class 'numpy.ndarray'>


1.5 Check Data Type

In [6]:
# Check data type
arr=np.array([1,2,3])
print(arr.dtype)

int64


1.6 Create Integer Array

In [7]:
# Integer array
arr=np.array([1.5,2.8,3.9],dtype=int)
print(arr)
print(arr.dtype)

[1 2 3]
int64


1.7 Create Float Array

In [8]:
# Float array
arr=np.array([1,2,3],dtype=float)
print(arr)
print(arr.dtype)

[1. 2. 3.]
float64


1.8 Create String Array

In [9]:
# String array
arr=np.array([1,2,3],dtype=str)
print(arr)
print(arr.dtype)

['1' '2' '3']
<U1


1.9 Create Array from Tuple

In [10]:
# Array from tuple
arr=np.array((10,20,30))
print(arr)

[10 20 30]


1.10 Create Array from List of Lists

In [11]:
# Array from nested lists
arr=np.array([[10,20],[30,40],[50,60]])
print(arr)

[[10 20]
 [30 40]
 [50 60]]


1.11 Array Dimensions

In [12]:
# Check dimensions
arr1=np.array([1,2,3])
arr2=np.array([[1,2],[3,4]])
arr3=np.array([[[1],[2]],[[3],[4]]])
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


1.12 Array Shape

In [13]:
# Check shape
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


1.13 Array Size

In [14]:
# Check size
arr=np.array([[1,2,3],[4,5,6]])
print(arr.size)

6


1.14 Array Length

In [15]:
# Length of first dimension
arr=np.array([5,10,15,20])
print(len(arr))

4


1.15 Array Item Size

In [16]:
# Memory used by one element
arr=np.array([1,2,3,4],dtype=np.int32)
print(arr.itemsize)

4


1.16 Total Memory Used

In [17]:
# Total memory usage
arr=np.array([1,2,3,4],dtype=np.int32)
print(arr.nbytes)

16


1.17 Convert Python List to NumPy Array

In [18]:
# Convert list to array
numbers=[10,20,30,40]
arr=np.array(numbers)
print(arr)

[10 20 30 40]


## **Phase 2: Special Array Creation**

2.1 Arrays with Default Values

In [19]:
# Zeros
print(np.zeros(5))
print(np.zeros((2,3)))

# Ones
print(np.ones(5))
print(np.ones((3,2)))

# Fill with a fixed value
print(np.full((2,4),7))

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[7 7 7 7]
 [7 7 7 7]]


2.2 Creating Sequences

In [20]:
# arange
print(np.arange(10))
print(np.arange(5,21,3))
print(np.arange(0,21,2))
print(np.arange(0,1,0.2))

# linspace
print(np.linspace(0,1,5))
print(np.linspace(10,50,10))

[0 1 2 3 4 5 6 7 8 9]
[ 5  8 11 14 17 20]
[ 0  2  4  6  8 10 12 14 16 18 20]
[0.  0.2 0.4 0.6 0.8]
[0.   0.25 0.5  0.75 1.  ]
[10.         14.44444444 18.88888889 23.33333333 27.77777778 32.22222222
 36.66666667 41.11111111 45.55555556 50.        ]


2.3 Identity Matrix

In [21]:
# Identity matrices
print(np.eye(3))
print(np.eye(4))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


2.4 Random Arrays

In [22]:
# Random decimal values
print(np.random.rand(5))
print(np.random.rand(2,3))

# Random integers
print(np.random.randint(1,10,5))
print(np.random.randint(10,100,(3,3)))

[0.32538345 0.71541533 0.93336551 0.2007755  0.44011507]
[[0.68325153 0.81436777 0.96271161]
 [0.13195009 0.07162276 0.64614796]]
[3 2 6 3 7]
[[96 77 37]
 [57 96 39]
 [35 55 31]]


## **Phase 3: Array Indexing and Slicing**

3.1 Accessing Elements

In [23]:
# Accessing elements
arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[2])
print(arr[-1])

10
30
50


3.2 Slicing 1D Arrays

In [24]:
# Slicing 1D arrays
arr=np.array([10,20,30,40,50,60])
print(arr[1:4])
print(arr[:3])
print(arr[3:])
print(arr[::2])

[20 30 40]
[10 20 30]
[40 50 60]
[10 30 50]


3.3 Accessing 2D Array Elements

In [25]:
# Accessing 2D array elements
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0,0])
print(arr[1,2])
print(arr[2,1])

1
6
8


3.4 Row and Column Selection

In [26]:
# Row and column selection
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0])
print(arr[1])
print(arr[:,0])
print(arr[:,2])

[1 2 3]
[4 5 6]
[1 4 7]
[3 6 9]


3.5 Slicing 2D Arrays

In [27]:
# Slicing 2D arrays
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0:2,1:3])
print(arr[:,1:])
print(arr[1:,0:2])

[[2 3]
 [5 6]]
[[2 3]
 [5 6]
 [8 9]]
[[4 5]
 [7 8]]


3.6 Modifying Array Values

In [28]:
# Modifying values
arr=np.array([10,20,30,40])
arr[1]=99
print(arr)

matrix=np.array([[1,2],[3,4]])
matrix[0,1]=100
print(matrix)

[10 99 30 40]
[[  1 100]
 [  3   4]]


3.7 Boolean Indexing

In [29]:
# Boolean indexing
arr=np.array([10,25,40,55,70])
print(arr[arr>30])
print(arr[arr%2==0])

[40 55 70]
[10 40 70]


3.8 Multiple Conditions

In [30]:
# Multiple conditions
arr=np.array([10,25,40,55,70,85])
print(arr[(arr>20) & (arr<80)])

[25 40 55 70]


3.9 Fancy Indexing

In [31]:
# Fancy indexing
arr=np.array([10,20,30,40,50])
print(arr[[0,2,4]])

matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[[0,2]])

[10 30 50]
[[1 2 3]
 [7 8 9]]


## **Phase 4: Array Reshaping**

4.1 Reshape a 1D Array

In [32]:
# Reshape a 1D array
arr=np.array([1,2,3,4,5,6])
print(arr.reshape(2,3))
print(arr.reshape(3,2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


4.2 Reshape a 2D Array

In [33]:
# Reshape a 2D array
arr=np.array([[1,2,3],[4,5,6]])
print(arr.reshape(1,6))
print(arr.reshape(6,1))

[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


4.3 Automatic Dimension with -1

In [34]:
# Automatic dimension calculation
arr=np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,-1))
print(arr.reshape(-1,4))

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


4.4 Flatten a Multi-Dimensional Array

In [35]:
# Flatten an array
arr=np.array([[1,2,3],[4,5,6]])
flat=arr.flatten()
print(flat)

[1 2 3 4 5 6]


4.5 Using ravel()

In [36]:
# Ravel an array
arr=np.array([[1,2,3],[4,5,6]])
flat=arr.ravel()
print(flat)

[1 2 3 4 5 6]


4.6 Transpose a Matrix

In [37]:
# Transpose using transpose()
arr=np.array([[1,2,3],[4,5,6]])
print(arr.transpose())

# Transpose using T
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


4.7 Change Shape Dynamically

In [38]:
# Dynamic reshaping
arr=np.arange(1,13)
matrix=arr.reshape(3,4)
print(matrix)

new_matrix=matrix.reshape(2,6)
print(new_matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


4.8 Convert Row Vector and Column Vector

In [39]:
# Row and column vectors
arr=np.array([10,20,30,40])

row=arr.reshape(1,4)
column=arr.reshape(4,1)

print(row)
print(column)

[[10 20 30 40]]
[[10]
 [20]
 [30]
 [40]]


## **Phase 5: Array Operations**

5.1 Basic Arithmetic Operations

In [40]:
# Basic arithmetic operations
a=np.array([10,20,30])
b=np.array([1,2,3])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


5.2 Scalar Operations

In [41]:
# Scalar operations
arr=np.array([5,10,15])

print(arr+5)
print(arr-2)
print(arr*3)
print(arr/5)

[10 15 20]
[ 3  8 13]
[15 30 45]
[1. 2. 3.]


5.3 Power and Modulus

In [42]:
# Power and modulus
arr=np.array([2,4,6,8])

print(arr**2)
print(arr%3)

[ 4 16 36 64]
[2 1 0 2]


5.4 Element-wise Operations on 2D Arrays

In [43]:
# Element-wise operations on matrices
a=np.array([[1,2],[3,4]])
b=np.array([[10,20],[30,40]])

print(a+b)
print(a*b)
print(a-b)

[[11 22]
 [33 44]]
[[ 10  40]
 [ 90 160]]
[[ -9 -18]
 [-27 -36]]


5.5 Comparison Operations

In [44]:
# Comparison operations
arr=np.array([10,25,40,55])

print(arr>30)
print(arr==25)
print(arr!=40)

[False False  True  True]
[False  True False False]
[ True  True False  True]


5.6 Using Comparison Results

In [45]:
# Filter values using comparisons
arr=np.array([10,25,40,55,70])

print(arr[arr>30])
print(arr[arr<50])

[40 55 70]
[10 25 40]


5.7 Mathematical Functions

In [46]:
# Common mathematical functions
arr=np.array([1,4,9,16])

print(np.sqrt(arr))
print(np.square(arr))
print(np.abs(np.array([-5,-2,3,-8])))

[1. 2. 3. 4.]
[  1  16  81 256]
[5 2 3 8]


5.8 Rounding Operations

In [47]:
# Rounding values
arr=np.array([10.235,20.789,30.456])

print(np.round(arr,2))
print(np.floor(arr))
print(np.ceil(arr))

[10.24 20.79 30.46]
[10. 20. 30.]
[11. 21. 31.]


5.9 Combining Multiple Operations

In [48]:
# Multiple operations together
sales=np.array([1000,1500,2000,2500])
discount=sales*0.1
final_price=sales-discount

print(discount)
print(final_price)

[100. 150. 200. 250.]
[ 900. 1350. 1800. 2250.]


## **Phase 6: Aggregation Functions**

6.1 Basic Aggregations

In [49]:
# Basic aggregations
arr=np.array([10,20,30,40,50])

print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.min(arr))
print(np.max(arr))

150
30.0
30.0
10
50


6.2 Standard Deviation and Variance

In [50]:
# Standard deviation and variance
arr=np.array([10,20,30,40,50])

print(np.std(arr))
print(np.var(arr))

14.142135623730951
200.0


6.3 Aggregations on a 2D Array

In [51]:
# 2D array aggregations
matrix=np.array([[10,20,30],[40,50,60],[70,80,90]])

print(np.sum(matrix))
print(np.mean(matrix))
print(np.max(matrix))
print(np.min(matrix))

450
50.0
90
10


6.4 Row-wise Calculations

In [52]:
# Row-wise calculations
matrix=np.array([[10,20,30],[40,50,60],[70,80,90]])

print(np.sum(matrix,axis=1))
print(np.mean(matrix,axis=1))
print(np.max(matrix,axis=1))

[ 60 150 240]
[20. 50. 80.]
[30 60 90]


6.5 Column-wise Calculations

In [53]:
# Column-wise calculations
matrix=np.array([[10,20,30],[40,50,60],[70,80,90]])

print(np.sum(matrix,axis=0))
print(np.mean(matrix,axis=0))
print(np.min(matrix,axis=0))

[120 150 180]
[40. 50. 60.]
[10 20 30]


6.6 Cumulative Operations

In [54]:
# Cumulative operations
arr=np.array([1,2,3,4,5])

print(np.cumsum(arr))
print(np.cumprod(arr))

[ 1  3  6 10 15]
[  1   2   6  24 120]


6.7 Find Index of Min and Max

In [55]:
# Index of min and max
arr=np.array([45,12,89,23,67])

print(np.argmin(arr))
print(np.argmax(arr))

1
2


6.8 Working with Sales Data

In [56]:
# Sales data analysis
sales=np.array([1200,1500,1700,1600,2000])

print("Total:",np.sum(sales))
print("Average:",np.mean(sales))
print("Highest:",np.max(sales))
print("Lowest:",np.min(sales))

Total: 8000
Average: 1600.0
Highest: 2000
Lowest: 1200


6.9 Working with Student Marks

In [57]:
# Student marks analysis
marks=np.array([[85,90,78],[92,88,95],[70,75,80]])

print("Average per student:")
print(np.mean(marks,axis=1))

print("Average per subject:")
print(np.mean(marks,axis=0))

Average per student:
[84.33333333 91.66666667 75.        ]
Average per subject:
[82.33333333 84.33333333 84.33333333]


## **Phase 7: Broadcasting**

7.1 Scalar Broadcasting

In [58]:
# Scalar broadcasting
arr=np.array([10,20,30,40])

print(arr+5)
print(arr*2)
print(arr/10)

[15 25 35 45]
[20 40 60 80]
[1. 2. 3. 4.]


7.2 Broadcasting with a Row Vector

In [59]:
# Row broadcasting
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
row=np.array([10,20,30])

print(matrix+row)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


7.3 Broadcasting with a Column Vector

In [60]:
# Column broadcasting
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
column=np.array([[100],[200],[300]])

print(matrix+column)

[[101 102 103]
 [204 205 206]
 [307 308 309]]


7.4 Different Shapes Working Together

In [61]:
# Different shapes
a=np.array([[1],[2],[3]])
b=np.array([10,20,30])

print(a+b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


7.5 Broadcasting in Multiplication

In [62]:
# Broadcasting multiplication
sales=np.array([[1000,1500,2000],[1200,1600,2200]])
growth=np.array([1.10,1.05,1.20])

updated_sales=sales*growth
print(updated_sales)

[[1100. 1575. 2400.]
 [1320. 1680. 2640.]]


7.6 Broadcasting with Division

In [63]:
# Broadcasting division
sales=np.array([[1000,1500,2000],[1200,1600,2200]])
targets=np.array([1000,1500,2000])

achievement=sales/targets
print(np.round(achievement,2))

[[1.   1.   1.  ]
 [1.2  1.07 1.1 ]]


7.7 Reshaping for Broadcasting

In [64]:
# Reshape for broadcasting
prices=np.array([100,200,300])
discount=np.array([5,10,15]).reshape(3,1)

print(prices-discount)

[[ 95 195 295]
 [ 90 190 290]
 [ 85 185 285]]


7.8 Broadcasting with Aggregation

In [65]:
# Subtract column means
data=np.array([[10,20,30],[40,50,60],[70,80,90]])

column_means=np.mean(data,axis=0)
centered=data-column_means

print(column_means)
print(centered)

[40. 50. 60.]
[[-30. -30. -30.]
 [  0.   0.   0.]
 [ 30.  30.  30.]]


## **Phase 8: Useful NumPy Functions**

8.1 Sorting Arrays

In [66]:
# Sorting arrays
arr=np.array([40,10,30,20,50])

print(np.sort(arr))
print(np.sort(arr)[::-1])

[10 20 30 40 50]
[50 40 30 20 10]


8.2 Sorting a 2D Array

In [67]:
# Sorting a 2D array
matrix=np.array([[3,1,2],[9,7,8]])

print(np.sort(matrix))
print(np.sort(matrix,axis=0))

[[1 2 3]
 [7 8 9]]
[[3 1 2]
 [9 7 8]]


8.3 Finding Unique Values

In [68]:
# Unique values
arr=np.array([10,20,20,30,30,30,40])

print(np.unique(arr))

[10 20 30 40]


8.4 Count Unique Values

In [69]:
# Unique values with counts
arr=np.array([1,2,2,3,3,3,4])

values,counts=np.unique(arr,return_counts=True)

print(values)
print(counts)

[1 2 3 4]
[1 2 3 1]


8.5 Concatenating Arrays

In [70]:
# Concatenate 1D arrays
a=np.array([1,2,3])
b=np.array([4,5,6])

print(np.concatenate((a,b)))

[1 2 3 4 5 6]


8.6 Concatenating 2D Arrays

In [71]:
# Concatenate 2D arrays
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

print(np.concatenate((a,b),axis=0))
print(np.concatenate((a,b),axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


8.7 Splitting Arrays

In [72]:
# Split arrays
arr=np.array([10,20,30,40,50,60])

print(np.split(arr,3))

[array([10, 20]), array([30, 40]), array([50, 60])]


8.8 Splitting a 2D Array

In [73]:
# Split a 2D array
matrix=np.array([[1,2],[3,4],[5,6],[7,8]])

print(np.vsplit(matrix,2))
print(np.hsplit(matrix,2))

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]
[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]


8.9 Using where()

In [74]:
# Find positions using where
arr=np.array([10,25,40,55,70])

print(np.where(arr>30))
print(np.where(arr%2==0))

(array([2, 3, 4]),)
(array([0, 2, 4]),)


8.10 Replace Values with where()

In [75]:
# Replace values conditionally
arr=np.array([10,-5,20,-2,30])

cleaned=np.where(arr<0,0,arr)

print(cleaned)

[10  0 20  0 30]


8.11 Clipping Values

In [76]:
# Limit values within a range
arr=np.array([5,15,25,35,45])

print(np.clip(arr,10,30))

[10 15 25 30 30]


8.12 Rounding Values

In [77]:
# Rounding values
arr=np.array([10.235,20.789,30.456])

print(np.round(arr,2))
print(np.round(arr))

[10.24 20.79 30.46]
[10. 21. 30.]


## **Phase 9: NumPy Random Module**

9.1 Set a Random Seed

In [78]:
# Set random seed
np.random.seed(42)

print(np.random.randint(1,10,5))

[7 4 8 5 7]


9.2 Generate Random Decimal Values

In [79]:
# Random decimal values
print(np.random.rand(5))
print(np.random.rand(2,3))

[0.44583275 0.09997492 0.45924889 0.33370861 0.14286682]
[[6.50888473e-01 5.64115790e-02 7.21998772e-01]
 [9.38552709e-01 7.78765841e-04 9.92211559e-01]]


9.3 Generate Random Numbers from Normal Distribution

In [80]:
# Random values from normal distribution
print(np.random.randn(5))
print(np.random.randn(2,3))

[ 1.46237812  1.53871497 -2.43910582  0.60344123 -0.25104397]
[[-0.16386712 -1.47632969  1.48698096]
 [-0.02445518  0.35555132  0.41701111]]


9.4 Generate Random Integers

In [81]:
# Random integers
print(np.random.randint(1,10,5))
print(np.random.randint(100,1000,(3,3)))

[9 7 2 4 9]
[[415 113 341]
 [876 445 664]
 [997 439 191]]


9.5 Select Random Values

In [82]:
# Random selection
items=np.array(["Laptop","Phone","Tablet","Monitor"])

print(np.random.choice(items))
print(np.random.choice(items,3))

Tablet
['Monitor' 'Tablet' 'Monitor']


9.6 Random Choice with Probabilities

In [83]:
# Weighted random choice
products=np.array(["A","B","C"])

print(np.random.choice(products,10,p=[0.6,0.3,0.1]))

['A' 'A' 'C' 'A' 'B' 'A' 'A' 'A' 'A' 'C']


9.7 Shuffle an Array

In [84]:
# Shuffle an array
arr=np.array([1,2,3,4,5,6])

np.random.shuffle(arr)

print(arr)

[1 3 5 6 4 2]


9.8 Generate Random Floating-Point Values in a Range

In [85]:
# Random values between 10 and 20
arr=np.random.uniform(10,20,5)

print(np.round(arr,2))

[19.27 17.27 13.27 15.7  15.21]


9.9 Create Sample Sales Data

In [86]:
# Simulated monthly sales data
np.random.seed(1)

sales=np.random.randint(1000,5000,12)

print(sales)
print("Average:",np.mean(sales))
print("Highest:",np.max(sales))

[2061 1235 4980 2096 4839 1905 3763 4717 3895 1960 1144 1129]
Average: 2810.3333333333335
Highest: 4980


## **Phase 10: Linear Algebra Basics**

10.1 Create Matrices

In [87]:
# Create matrices
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


10.2 Element-wise Multiplication

In [88]:
# Element-wise multiplication
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

print(a*b)

[[ 5 12]
 [21 32]]


10.3 Matrix Multiplication

In [89]:
# Matrix multiplication
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

print(np.dot(a,b))
print(a@b)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


10.4 Transpose of a Matrix

In [90]:
# Transpose of a matrix
matrix=np.array([[1,2,3],[4,5,6]])

print(matrix.transpose())
print(matrix.T)

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


10.5 Determinant

In [91]:
# Determinant of a matrix
matrix=np.array([[2,1],[5,3]])

print(np.linalg.det(matrix))

1.0000000000000009


10.6 Inverse of a Matrix

In [92]:
# Inverse of a matrix
matrix=np.array([[4,7],[2,6]])

inverse=np.linalg.inv(matrix)

print(inverse)

[[ 0.6 -0.7]
 [-0.2  0.4]]


10.7 Verify the Inverse

In [93]:
# Verify inverse
matrix=np.array([[4,7],[2,6]])

inverse=np.linalg.inv(matrix)

print(np.round(matrix@inverse,2))

[[ 1. -0.]
 [ 0.  1.]]


10.8 Eigenvalues and Eigenvectors

In [94]:
# Eigenvalues and eigenvectors
matrix=np.array([[2,1],[1,2]])

values,vectors=np.linalg.eig(matrix)

print(values)
print(vectors)

[3. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


10.9 Solve a Linear System

In [95]:
# Solve linear equations
# 2x + y = 5
# x + 3y = 6

A=np.array([[2,1],[1,3]])
B=np.array([5,6])

solution=np.linalg.solve(A,B)

print(solution)

[1.8 1.4]


10.10 Matrix Statistics

In [96]:
# Matrix statistics
sales=np.array([[1200,1500,1700],[1600,1800,2000],[2100,2200,2400]])

print(np.sum(sales))
print(np.mean(sales))
print(np.max(sales))
print(np.min(sales))

16500
1833.3333333333333
2400
1200


## **Phase 12: Summary**

**Topics Covered**

- Creating Arrays

- Special Array Creation

- Array Indexing and Slicing

- Array Reshaping

- Array Operations

- Aggregation Functions

- Broadcasting

- Useful NumPy Functions

- NumPy Random Module

- Linear Algebra Basics
